In [35]:
from mxnet import nd,autograd
import numpy as np

In [6]:
x=nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [6]:
x.shape

(12,)

In [7]:
x.size

12

In [8]:
X=x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [9]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [10]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [7]:
Y=nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

In [13]:
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [14]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [15]:
X+Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [16]:
X*Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [17]:
X/Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [18]:
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [19]:
X,Y

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[2. 1. 4. 3.]
  [1. 2. 3. 4.]
  [4. 3. 2. 1.]]
 <NDArray 3x4 @cpu(0)>)

In [20]:
nd.dot(X,Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [21]:
nd.concat(X,Y,dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [22]:
nd.concat(X,Y,dim=1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [23]:
X,Y

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[2. 1. 4. 3.]
  [1. 2. 3. 4.]
  [4. 3. 2. 1.]]
 <NDArray 3x4 @cpu(0)>)

In [24]:
X==Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [25]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [26]:
A = nd.arange(3).reshape((3,1))

In [27]:
A


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

In [28]:
B=nd.arange(2).reshape((2,1))

In [29]:
A,B


(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0.]
  [1.]]
 <NDArray 2x1 @cpu(0)>)

In [30]:
B=reshape((1,2))

NameError: name 'reshape' is not defined

In [31]:
A+B

MXNetError: Traceback (most recent call last):
  File "c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\numpy\linalg\../../tensor/elemwise_binary_broadcast_op.h", line 68
MXNetError: Check failed: l == 1 || r == 1: operands could not be broadcast together with shapes [3,1] [2,1]

In [33]:
B = nd.arange(2).shape((1,2))

TypeError: 'tuple' object is not callable

In [34]:
B = nd.arange(2).reshape((1,2))

In [35]:
A,B


(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [36]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

## 2.2.4 索引 

In [3]:
X

NameError: name 'X' is not defined

In [4]:
x=nd.arange(12)

NameError: name 'nd' is not defined

In [9]:
X,Y

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[2. 1. 4. 3.]
  [1. 2. 3. 4.]
  [4. 3. 2. 1.]]
 <NDArray 3x4 @cpu(0)>)

In [10]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [11]:
X[1,2]


[6.]
<NDArray 1 @cpu(0)>

In [12]:
X[1,2]=9

In [13]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [14]:
X[1:2]=12

In [15]:
X



[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [16]:
X[1:3,:]=12

In [17]:
X



[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

## 2.2.5 运算的内存开销

In [18]:
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [19]:
before=id(Y)

In [20]:
before

2149071197408

In [21]:
Y=Y+X

In [22]:
before=id(Y)

In [23]:
before

2148028069480

In [24]:
Z=Y.zeros_like()

In [25]:
Z


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [26]:
before=id(Z)

In [27]:
Z[:]=X+Y

In [28]:
Z


[[ 2.  3.  8.  9.]
 [25. 26. 27. 28.]
 [28. 27. 26. 25.]]
<NDArray 3x4 @cpu(0)>

In [29]:
id(Z)==before

True

In [30]:
nd.elemwise_add(X,Y,out=Z)


[[ 2.  3.  8.  9.]
 [25. 26. 27. 28.]
 [28. 27. 26. 25.]]
<NDArray 3x4 @cpu(0)>

In [31]:
id(Z)==before

True

In [33]:
P=np.ones((2,3))
D=nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [34]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)